# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7653c87a28d08eb05b59c6ea6a03a7c941924e9a12fa52643f619c0a2360d5d2430fe0896a6785f1f479340621d348bc372e67a0d73fbcbedf62fee5aba40721

test:
  secret_key_base: 37f1320eb50d09c63141b24decabcf50e93ebcb307cb03ab8d97589edf4b780dfebd6ee56aea366f43a1d8fe7fbd0f53b684d0f39255e5800752507806ef5421

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
